firefly = ['Halsey', 'My Chemical Romance', 'Green Day', 'Dua Lipa', 'Weezer', 'The Kid Laroi', 'Big Sean' 'Zedd', 'Porter Robinson', 'Gunna', 'Avril Lavigne', 'Jamie XX', 'Gryffin', 'Charlie XCX', 'Bleachers', 'Rainbow Kitten Surprise', 'The Head and the Heart', 'Jungle', 'Conan Gray', 'All Time Low', 'Yungblud', 'Saint JHN', 'Cordae', 'Willow', 'Ashnikko', 'Manchester Orchestra', 'Cold War Kids', '100 Gecs', 'Dayglow', 'Girl Talk', 'Wolf Alice', 'The Regrettes']

bonnaroo = ['Gryffin', 'Clozee', 'Sidepiece', 'Role Model', 'The Brook & the Bluff', 'J. Cole', 'The Chicks', 'Illenium', 'Robert Plant & Alison Krauss', 'Disclosure', 'Lord Huron', 'The War on Drugs', 'King Gizzard & the Lizard Wizard', 'Goose', 'Bleachers', 'Denzel Curry', 'Tove Lo', 'The Regrettes', 'Tool', 'Flume', '21 Savage', 'Billy Strings', '$uicideboy$', 'Porter Robinson', 'Marc Rebillet', 'Chvrches', 'Lany', 'Ludacris', '100 Gecs', 'All Time Low', 'Stevie Nicks', 'Machine Gun Kelly', 'Roddy Ricch', 'Nathaniel Rateliff& the Nightsweats', 'Rezz', 'Tash Sultana']

coachella = ['Harry Styles', 'Lil Baby', 'Daniel Ceasar', 'Pheobe Bridgers', 'Big Sean', 'Grupo Firme', 'Louis the Child', 'Baby Keem', 'Still Woozy', 'King Gizzard & the Lizard Wizard', 'Bishop Briggs', 'Role Model', 'The Regrettes', 'the Hu', 'Billie Eilish', 'Flume', 'Megan Thee Stallion', 'Discosure', '21 Savage', 'Danny Elfman', 'girl in red', 'Conan Gray', '100 Gecs', 'Emo Nite', 'Ye', 'Doja Cat', 'Joji', 'Jamie XX', 'Run the Jewels', 'Karol G', 'Maggie Rogers', 'Fatboy Slim', 'Denzel Curry', 'Finneas', 'Vince Staples', 'Swedish House Mafia', '88 Rising']

lollapalooza = ['Metallica', 'Dua Lipa', 'J. Cole', 'Green Day', 'Doja Cat', 'Machine Gun Kelly', 'Lil Baby', 'Kygo', 'Glass Animals', 'Billy Strings', 'Big Sean', 'The Kid Laroi', 'Jazmine Sullivan', 'Don Toliver', 'Charli XCX', 'Idles', 'Turnstile', 'Kaskade', 'Rezz', 'Zhu', 'YG', 'Dominic Fike', 'King Princess', 'Wallows', 'Still Woozy', '100 Gecs', 'Girl in Red', 'Ashnikko', 'Denzel Curry', 'Willow', 'Royal Blood', 'Manchester Orchestra', 'Tove Lo', 'Bob Moses', 'Banks', 'Remi Wolf', 'Dashboard Confessional', 'Role Model', 'Wet Leg', 'The Wombats', 'The Regrettes', 'Kennyhoopla', 'Jane\'s Addiction']

shaky_knees = ['Green Day', 'Nine Inch Nails', 'My Morning Jacket', 'Rainbow Kitten Surprise', 'Dropkick Murphys', 'Chvches', 'King Gizzard & the Lizard Wizard', 'Khruangbin', 'Death Cab for Cutie', 'Spoon', 'Highly Suspect', 'Lennon Stella', 'Grandson', 'Mt. Joy', 'Gang of Youths', 'The Regrettes', 'Phanton Planet', 'Band of Horses', 'The Glorious Sons', 'Coin', 'Colony House', 'Pup', 'The Happy Fits', 'Dirty Honey']

hangout_fest = ['Post Malone', 'Fall Out Boy', 'Kane Brown', 'Zedd', 'Maren Morris', 'Oliver Tree', 'T-Pain', 'Surfaces', 'Koffee', 'Dayglow', 'Remi Wolf', 'Halsey', 'Doja Cat', 'Illenium', 'Leon Bridges', 'Still Woozy', 'The Band Camino', 'Lil Yachty', 'Chelsea Cutler', 'Flo Milli', 'Madeon', 'Role Model', 'Tame Impala', 'Megan Thee Stallion', 'Jack Harlow', 'Phoebe Bridgers', 'Louis the Child', 'Slander', 'The Head and the Heart', 'Sublime with Rome', 'Fletcher', 'Kennyhoopla']

boston_calling = ['Nine Inch Nails', 'Rufus Du Sol', 'Haim', 'Avril Lavigne', 'Cheap Trick', 'Oliver Tree', 'The Struts', 'Paris Jackson', 'Grandson', 'The Strokes', 'Run the Jewels', 'King Gizzard & the Lizard Wizard', 'Black Pumas', 'Kennyhoopla', 'Metallica', 'Weezer', 'Glass Animals', 'Modest Mouse', 'Goose', 'Ripe', 'Cults', 'Peach Tree Rascals']

lightning_in_a_bottle = ['Glass Animals', 'Big Wild', 'Chet Faker', 'Seth Troxler', 'Koffee', 'Kaytranada', 'Four Tet', 'Clozee', 'Griz', 'Black Coffee', 'SG Lewis', 'Ekali']

camping = ['Firefly Festival', 'Bonnaroo', 'Coachella', 'Lightning in a Bottle']

non_camping = ['Lollapalooza', 'Shaky Knees', 'Hangout Fest', 'Boston Calling']
